server:
  port: 8080

spring:
    datasource:
        name: blog
        url: jdbc:oracle:thin:@10.100.3.182:1521:UATDB11g
        username: LTRUCK
        password: Yx5353
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:sqlMap/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zcf.springbootmybatis.pojo  # 注意：对应实体类的路径