package com.zcf.springbootmybatis.dao;

import com.zcf.springbootmybatis.pojo.TWtd;
import org.springframework.stereotype.Component;

public interface TWtdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int deleteByPrimaryKey(Long wtdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int insert(TWtd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int insertSelective(TWtd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    TWtd selectByPrimaryKey(Long wtdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int updateByPrimaryKeySelective(TWtd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int updateByPrimaryKey(TWtd record);
}