package com.zcf.springbootmybatis.dao;

import com.zcf.springbootmybatis.pojo.TZxd;
import org.springframework.stereotype.Component;

public interface TZxdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_ZXD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int deleteByPrimaryKey(Long xhid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_ZXD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int insert(TZxd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_ZXD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int insertSelective(TZxd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_ZXD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    TZxd selectByPrimaryKey(Long xhid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_ZXD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int updateByPrimaryKeySelective(TZxd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LTRUCK.T_ZXD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    int updateByPrimaryKey(TZxd record);
}