package com.zcf.springbootmybatis.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TWtd implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.WTDID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Long wtdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.COMP_ID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Long compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.BMMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String bmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.YWBH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String ywbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.TDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String tdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.WTRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date wtrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.WTDW
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String wtdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.WTDWMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String wtdwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.LXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String lxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.LXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String lxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CXZX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cxzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.BZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.TDYFBZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String tdyfbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.XXXCS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String xxxcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.BXS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private BigDecimal bxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SRRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String srry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SRSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date srsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.XGRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String xgry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.XGSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date xgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ZZG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String zzg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.MDG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String mdg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SDYWBH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String sdywbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.JGRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date jgrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.KFRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String kfry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.YWRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String ywry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.YWLX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String ywlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SBDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String sbdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ECCM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String eccm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ECHC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String echc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ZZBS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String zzbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CDL
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ZHG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String zhg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.KHRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date khrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.DGRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date dgrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.FKFS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String fkfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HWLX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hwlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ZWHM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String zwhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.JS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private BigDecimal js;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.MZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private BigDecimal mz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.TJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private BigDecimal tj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.ZHZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private BigDecimal zhz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CGS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.PDRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date pdrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.YSTK
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String ystk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.WTDSD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String wtdsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SDRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String sdry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SDSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date sdsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CWSD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cwsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.JXQSSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date jxqssj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.JXZZSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private Date jxzzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.WORKNO
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String workno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SNDDEAID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String snddeaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CDLXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cdlxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.CDLXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String cdlxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HZDWMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hzdwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HZEDIID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hzediid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HZLXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hzlxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HZLXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hzlxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.HDEDIID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String hdediid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.SOURCE_HWDID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String sourceHwdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.LDG_DATA_FLAG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String ldgDataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LTRUCK.T_WTD.YWLXMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private String ywlxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LTRUCK.T_WTD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.WTDID
     *
     * @return the value of LTRUCK.T_WTD.WTDID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Long getWtdid() {
        return wtdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.WTDID
     *
     * @param wtdid the value for LTRUCK.T_WTD.WTDID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setWtdid(Long wtdid) {
        this.wtdid = wtdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.COMP_ID
     *
     * @return the value of LTRUCK.T_WTD.COMP_ID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Long getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.COMP_ID
     *
     * @param compId the value for LTRUCK.T_WTD.COMP_ID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCompId(Long compId) {
        this.compId = compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.BMMC
     *
     * @return the value of LTRUCK.T_WTD.BMMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.BMMC
     *
     * @param bmmc the value for LTRUCK.T_WTD.BMMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc == null ? null : bmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.YWBH
     *
     * @return the value of LTRUCK.T_WTD.YWBH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getYwbh() {
        return ywbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.YWBH
     *
     * @param ywbh the value for LTRUCK.T_WTD.YWBH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setYwbh(String ywbh) {
        this.ywbh = ywbh == null ? null : ywbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.TDH
     *
     * @return the value of LTRUCK.T_WTD.TDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getTdh() {
        return tdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.TDH
     *
     * @param tdh the value for LTRUCK.T_WTD.TDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setTdh(String tdh) {
        this.tdh = tdh == null ? null : tdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.WTRQ
     *
     * @return the value of LTRUCK.T_WTD.WTRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getWtrq() {
        return wtrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.WTRQ
     *
     * @param wtrq the value for LTRUCK.T_WTD.WTRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setWtrq(Date wtrq) {
        this.wtrq = wtrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.WTDW
     *
     * @return the value of LTRUCK.T_WTD.WTDW
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getWtdw() {
        return wtdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.WTDW
     *
     * @param wtdw the value for LTRUCK.T_WTD.WTDW
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setWtdw(String wtdw) {
        this.wtdw = wtdw == null ? null : wtdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.WTDWMC
     *
     * @return the value of LTRUCK.T_WTD.WTDWMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getWtdwmc() {
        return wtdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.WTDWMC
     *
     * @param wtdwmc the value for LTRUCK.T_WTD.WTDWMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setWtdwmc(String wtdwmc) {
        this.wtdwmc = wtdwmc == null ? null : wtdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.LXR
     *
     * @return the value of LTRUCK.T_WTD.LXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.LXR
     *
     * @param lxr the value for LTRUCK.T_WTD.LXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.LXDH
     *
     * @return the value of LTRUCK.T_WTD.LXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.LXDH
     *
     * @param lxdh the value for LTRUCK.T_WTD.LXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CM
     *
     * @return the value of LTRUCK.T_WTD.CM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCm() {
        return cm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CM
     *
     * @param cm the value for LTRUCK.T_WTD.CM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCm(String cm) {
        this.cm = cm == null ? null : cm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HC
     *
     * @return the value of LTRUCK.T_WTD.HC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHc() {
        return hc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HC
     *
     * @param hc the value for LTRUCK.T_WTD.HC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHc(String hc) {
        this.hc = hc == null ? null : hc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CXZX
     *
     * @return the value of LTRUCK.T_WTD.CXZX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCxzx() {
        return cxzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CXZX
     *
     * @param cxzx the value for LTRUCK.T_WTD.CXZX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCxzx(String cxzx) {
        this.cxzx = cxzx == null ? null : cxzx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.BZ
     *
     * @return the value of LTRUCK.T_WTD.BZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.BZ
     *
     * @param bz the value for LTRUCK.T_WTD.BZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.TDYFBZ
     *
     * @return the value of LTRUCK.T_WTD.TDYFBZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getTdyfbz() {
        return tdyfbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.TDYFBZ
     *
     * @param tdyfbz the value for LTRUCK.T_WTD.TDYFBZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setTdyfbz(String tdyfbz) {
        this.tdyfbz = tdyfbz == null ? null : tdyfbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.XXXCS
     *
     * @return the value of LTRUCK.T_WTD.XXXCS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getXxxcs() {
        return xxxcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.XXXCS
     *
     * @param xxxcs the value for LTRUCK.T_WTD.XXXCS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setXxxcs(String xxxcs) {
        this.xxxcs = xxxcs == null ? null : xxxcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.BXS
     *
     * @return the value of LTRUCK.T_WTD.BXS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public BigDecimal getBxs() {
        return bxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.BXS
     *
     * @param bxs the value for LTRUCK.T_WTD.BXS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setBxs(BigDecimal bxs) {
        this.bxs = bxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SRRY
     *
     * @return the value of LTRUCK.T_WTD.SRRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getSrry() {
        return srry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SRRY
     *
     * @param srry the value for LTRUCK.T_WTD.SRRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSrry(String srry) {
        this.srry = srry == null ? null : srry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SRSJ
     *
     * @return the value of LTRUCK.T_WTD.SRSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getSrsj() {
        return srsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SRSJ
     *
     * @param srsj the value for LTRUCK.T_WTD.SRSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSrsj(Date srsj) {
        this.srsj = srsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.XGRY
     *
     * @return the value of LTRUCK.T_WTD.XGRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getXgry() {
        return xgry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.XGRY
     *
     * @param xgry the value for LTRUCK.T_WTD.XGRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setXgry(String xgry) {
        this.xgry = xgry == null ? null : xgry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.XGSJ
     *
     * @return the value of LTRUCK.T_WTD.XGSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getXgsj() {
        return xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.XGSJ
     *
     * @param xgsj the value for LTRUCK.T_WTD.XGSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setXgsj(Date xgsj) {
        this.xgsj = xgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ZZG
     *
     * @return the value of LTRUCK.T_WTD.ZZG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getZzg() {
        return zzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ZZG
     *
     * @param zzg the value for LTRUCK.T_WTD.ZZG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setZzg(String zzg) {
        this.zzg = zzg == null ? null : zzg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.MDG
     *
     * @return the value of LTRUCK.T_WTD.MDG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getMdg() {
        return mdg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.MDG
     *
     * @param mdg the value for LTRUCK.T_WTD.MDG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setMdg(String mdg) {
        this.mdg = mdg == null ? null : mdg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SDYWBH
     *
     * @return the value of LTRUCK.T_WTD.SDYWBH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getSdywbh() {
        return sdywbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SDYWBH
     *
     * @param sdywbh the value for LTRUCK.T_WTD.SDYWBH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSdywbh(String sdywbh) {
        this.sdywbh = sdywbh == null ? null : sdywbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.JGRQ
     *
     * @return the value of LTRUCK.T_WTD.JGRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getJgrq() {
        return jgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.JGRQ
     *
     * @param jgrq the value for LTRUCK.T_WTD.JGRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setJgrq(Date jgrq) {
        this.jgrq = jgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.KFRY
     *
     * @return the value of LTRUCK.T_WTD.KFRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getKfry() {
        return kfry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.KFRY
     *
     * @param kfry the value for LTRUCK.T_WTD.KFRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setKfry(String kfry) {
        this.kfry = kfry == null ? null : kfry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.YWRY
     *
     * @return the value of LTRUCK.T_WTD.YWRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getYwry() {
        return ywry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.YWRY
     *
     * @param ywry the value for LTRUCK.T_WTD.YWRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setYwry(String ywry) {
        this.ywry = ywry == null ? null : ywry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.YWLX
     *
     * @return the value of LTRUCK.T_WTD.YWLX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getYwlx() {
        return ywlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.YWLX
     *
     * @param ywlx the value for LTRUCK.T_WTD.YWLX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setYwlx(String ywlx) {
        this.ywlx = ywlx == null ? null : ywlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SBDH
     *
     * @return the value of LTRUCK.T_WTD.SBDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getSbdh() {
        return sbdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SBDH
     *
     * @param sbdh the value for LTRUCK.T_WTD.SBDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSbdh(String sbdh) {
        this.sbdh = sbdh == null ? null : sbdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ECCM
     *
     * @return the value of LTRUCK.T_WTD.ECCM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getEccm() {
        return eccm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ECCM
     *
     * @param eccm the value for LTRUCK.T_WTD.ECCM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setEccm(String eccm) {
        this.eccm = eccm == null ? null : eccm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ECHC
     *
     * @return the value of LTRUCK.T_WTD.ECHC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getEchc() {
        return echc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ECHC
     *
     * @param echc the value for LTRUCK.T_WTD.ECHC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setEchc(String echc) {
        this.echc = echc == null ? null : echc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ZZBS
     *
     * @return the value of LTRUCK.T_WTD.ZZBS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getZzbs() {
        return zzbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ZZBS
     *
     * @param zzbs the value for LTRUCK.T_WTD.ZZBS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setZzbs(String zzbs) {
        this.zzbs = zzbs == null ? null : zzbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CDL
     *
     * @return the value of LTRUCK.T_WTD.CDL
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCdl() {
        return cdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CDL
     *
     * @param cdl the value for LTRUCK.T_WTD.CDL
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCdl(String cdl) {
        this.cdl = cdl == null ? null : cdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ZHG
     *
     * @return the value of LTRUCK.T_WTD.ZHG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getZhg() {
        return zhg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ZHG
     *
     * @param zhg the value for LTRUCK.T_WTD.ZHG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setZhg(String zhg) {
        this.zhg = zhg == null ? null : zhg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.KHRQ
     *
     * @return the value of LTRUCK.T_WTD.KHRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getKhrq() {
        return khrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.KHRQ
     *
     * @param khrq the value for LTRUCK.T_WTD.KHRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setKhrq(Date khrq) {
        this.khrq = khrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.DGRQ
     *
     * @return the value of LTRUCK.T_WTD.DGRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getDgrq() {
        return dgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.DGRQ
     *
     * @param dgrq the value for LTRUCK.T_WTD.DGRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setDgrq(Date dgrq) {
        this.dgrq = dgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.FKFS
     *
     * @return the value of LTRUCK.T_WTD.FKFS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getFkfs() {
        return fkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.FKFS
     *
     * @param fkfs the value for LTRUCK.T_WTD.FKFS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setFkfs(String fkfs) {
        this.fkfs = fkfs == null ? null : fkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HWLX
     *
     * @return the value of LTRUCK.T_WTD.HWLX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHwlx() {
        return hwlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HWLX
     *
     * @param hwlx the value for LTRUCK.T_WTD.HWLX
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHwlx(String hwlx) {
        this.hwlx = hwlx == null ? null : hwlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ZWHM
     *
     * @return the value of LTRUCK.T_WTD.ZWHM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getZwhm() {
        return zwhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ZWHM
     *
     * @param zwhm the value for LTRUCK.T_WTD.ZWHM
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setZwhm(String zwhm) {
        this.zwhm = zwhm == null ? null : zwhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.JS
     *
     * @return the value of LTRUCK.T_WTD.JS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public BigDecimal getJs() {
        return js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.JS
     *
     * @param js the value for LTRUCK.T_WTD.JS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setJs(BigDecimal js) {
        this.js = js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.MZ
     *
     * @return the value of LTRUCK.T_WTD.MZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public BigDecimal getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.MZ
     *
     * @param mz the value for LTRUCK.T_WTD.MZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setMz(BigDecimal mz) {
        this.mz = mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.TJ
     *
     * @return the value of LTRUCK.T_WTD.TJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public BigDecimal getTj() {
        return tj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.TJ
     *
     * @param tj the value for LTRUCK.T_WTD.TJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setTj(BigDecimal tj) {
        this.tj = tj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.ZHZ
     *
     * @return the value of LTRUCK.T_WTD.ZHZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public BigDecimal getZhz() {
        return zhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.ZHZ
     *
     * @param zhz the value for LTRUCK.T_WTD.ZHZ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setZhz(BigDecimal zhz) {
        this.zhz = zhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CGS
     *
     * @return the value of LTRUCK.T_WTD.CGS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCgs() {
        return cgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CGS
     *
     * @param cgs the value for LTRUCK.T_WTD.CGS
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCgs(String cgs) {
        this.cgs = cgs == null ? null : cgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.PDRQ
     *
     * @return the value of LTRUCK.T_WTD.PDRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getPdrq() {
        return pdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.PDRQ
     *
     * @param pdrq the value for LTRUCK.T_WTD.PDRQ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setPdrq(Date pdrq) {
        this.pdrq = pdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.YSTK
     *
     * @return the value of LTRUCK.T_WTD.YSTK
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getYstk() {
        return ystk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.YSTK
     *
     * @param ystk the value for LTRUCK.T_WTD.YSTK
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setYstk(String ystk) {
        this.ystk = ystk == null ? null : ystk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.WTDSD
     *
     * @return the value of LTRUCK.T_WTD.WTDSD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getWtdsd() {
        return wtdsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.WTDSD
     *
     * @param wtdsd the value for LTRUCK.T_WTD.WTDSD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setWtdsd(String wtdsd) {
        this.wtdsd = wtdsd == null ? null : wtdsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SDRY
     *
     * @return the value of LTRUCK.T_WTD.SDRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getSdry() {
        return sdry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SDRY
     *
     * @param sdry the value for LTRUCK.T_WTD.SDRY
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSdry(String sdry) {
        this.sdry = sdry == null ? null : sdry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SDSJ
     *
     * @return the value of LTRUCK.T_WTD.SDSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getSdsj() {
        return sdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SDSJ
     *
     * @param sdsj the value for LTRUCK.T_WTD.SDSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSdsj(Date sdsj) {
        this.sdsj = sdsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CWSD
     *
     * @return the value of LTRUCK.T_WTD.CWSD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCwsd() {
        return cwsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CWSD
     *
     * @param cwsd the value for LTRUCK.T_WTD.CWSD
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCwsd(String cwsd) {
        this.cwsd = cwsd == null ? null : cwsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.JXQSSJ
     *
     * @return the value of LTRUCK.T_WTD.JXQSSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getJxqssj() {
        return jxqssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.JXQSSJ
     *
     * @param jxqssj the value for LTRUCK.T_WTD.JXQSSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setJxqssj(Date jxqssj) {
        this.jxqssj = jxqssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.JXZZSJ
     *
     * @return the value of LTRUCK.T_WTD.JXZZSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public Date getJxzzsj() {
        return jxzzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.JXZZSJ
     *
     * @param jxzzsj the value for LTRUCK.T_WTD.JXZZSJ
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setJxzzsj(Date jxzzsj) {
        this.jxzzsj = jxzzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.WORKNO
     *
     * @return the value of LTRUCK.T_WTD.WORKNO
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getWorkno() {
        return workno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.WORKNO
     *
     * @param workno the value for LTRUCK.T_WTD.WORKNO
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setWorkno(String workno) {
        this.workno = workno == null ? null : workno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SNDDEAID
     *
     * @return the value of LTRUCK.T_WTD.SNDDEAID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getSnddeaid() {
        return snddeaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SNDDEAID
     *
     * @param snddeaid the value for LTRUCK.T_WTD.SNDDEAID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSnddeaid(String snddeaid) {
        this.snddeaid = snddeaid == null ? null : snddeaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CDLXR
     *
     * @return the value of LTRUCK.T_WTD.CDLXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCdlxr() {
        return cdlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CDLXR
     *
     * @param cdlxr the value for LTRUCK.T_WTD.CDLXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCdlxr(String cdlxr) {
        this.cdlxr = cdlxr == null ? null : cdlxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.CDLXDH
     *
     * @return the value of LTRUCK.T_WTD.CDLXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getCdlxdh() {
        return cdlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.CDLXDH
     *
     * @param cdlxdh the value for LTRUCK.T_WTD.CDLXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setCdlxdh(String cdlxdh) {
        this.cdlxdh = cdlxdh == null ? null : cdlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HZDWMC
     *
     * @return the value of LTRUCK.T_WTD.HZDWMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHzdwmc() {
        return hzdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HZDWMC
     *
     * @param hzdwmc the value for LTRUCK.T_WTD.HZDWMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHzdwmc(String hzdwmc) {
        this.hzdwmc = hzdwmc == null ? null : hzdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HZEDIID
     *
     * @return the value of LTRUCK.T_WTD.HZEDIID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHzediid() {
        return hzediid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HZEDIID
     *
     * @param hzediid the value for LTRUCK.T_WTD.HZEDIID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHzediid(String hzediid) {
        this.hzediid = hzediid == null ? null : hzediid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HZLXR
     *
     * @return the value of LTRUCK.T_WTD.HZLXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHzlxr() {
        return hzlxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HZLXR
     *
     * @param hzlxr the value for LTRUCK.T_WTD.HZLXR
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHzlxr(String hzlxr) {
        this.hzlxr = hzlxr == null ? null : hzlxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HZLXDH
     *
     * @return the value of LTRUCK.T_WTD.HZLXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHzlxdh() {
        return hzlxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HZLXDH
     *
     * @param hzlxdh the value for LTRUCK.T_WTD.HZLXDH
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHzlxdh(String hzlxdh) {
        this.hzlxdh = hzlxdh == null ? null : hzlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.HDEDIID
     *
     * @return the value of LTRUCK.T_WTD.HDEDIID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getHdediid() {
        return hdediid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.HDEDIID
     *
     * @param hdediid the value for LTRUCK.T_WTD.HDEDIID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setHdediid(String hdediid) {
        this.hdediid = hdediid == null ? null : hdediid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.SOURCE_HWDID
     *
     * @return the value of LTRUCK.T_WTD.SOURCE_HWDID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getSourceHwdid() {
        return sourceHwdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.SOURCE_HWDID
     *
     * @param sourceHwdid the value for LTRUCK.T_WTD.SOURCE_HWDID
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setSourceHwdid(String sourceHwdid) {
        this.sourceHwdid = sourceHwdid == null ? null : sourceHwdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.LDG_DATA_FLAG
     *
     * @return the value of LTRUCK.T_WTD.LDG_DATA_FLAG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getLdgDataFlag() {
        return ldgDataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.LDG_DATA_FLAG
     *
     * @param ldgDataFlag the value for LTRUCK.T_WTD.LDG_DATA_FLAG
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setLdgDataFlag(String ldgDataFlag) {
        this.ldgDataFlag = ldgDataFlag == null ? null : ldgDataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LTRUCK.T_WTD.YWLXMC
     *
     * @return the value of LTRUCK.T_WTD.YWLXMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public String getYwlxmc() {
        return ywlxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LTRUCK.T_WTD.YWLXMC
     *
     * @param ywlxmc the value for LTRUCK.T_WTD.YWLXMC
     *
     * @mbg.generated Sat Aug 03 08:53:58 CST 2019
     */
    public void setYwlxmc(String ywlxmc) {
        this.ywlxmc = ywlxmc == null ? null : ywlxmc.trim();
    }
}